dist: xenial
language: node_js
cache:
  directories:
    - "$HOME/google-cloud-sdk"
env:
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1 CLOUD_PROJECT=august-strata-281417 CLOUD_REGION=europe-west1 CLOUD_FUNCTION_NAME=bindery-recaller PUBSUB_TOPIC_NAME=unpublish
before_install:
  - openssl aes-256-cbc -K $encrypted_4cca25746a52_key -iv $encrypted_4cca25746a52_iv -in service-account-travis-ci.json.enc -out service-account-travis-ci.json -d
  - if [ ! -d ${HOME}/google-cloud-sdk/bin ]; then
      rm -rf $HOME/google-cloud-sdk;
      curl https://sdk.cloud.google.com | bash > /dev/null;
    fi
  - source "$HOME/google-cloud-sdk/path.bash.inc"
  - gcloud version
  - gcloud auth activate-service-account --key-file service-account-travis-ci.json
install:
  - gcloud config set project $CLOUD_PROJECT
  - yarn --frozen-lockfile
script:
  - yarn test
deploy:
  provicer: script
  script: ./deploy.sh
  skip_cleanup: true
  on:
    branch: master
