language: node_js
cache:
  yarn: true
  directories:
    - "node_modules"
    - "$HOME/google-cloud-sdk/"
env:
  - GOOGLE_CLOUD_PROJECT=august-strata-281417 CLOUD_FUNCTION_NAME=bindery-recaller PUBSUB_TOPIC_NAME=unpublish
before_install:
  - openssl aes-256-cbc -K $encrypted_4cca25746a52_key -iv $encrypted_4cca25746a52_iv -in service-account-travis-ci.json.enc -out service-account-travis-ci.json -d
  - if [ ! -d ${HOME}/google-cloud-sdk ]; then
      curl https://sdk.cloud.google.com | bash;
    fi
  - gcloud auth activate-service-account --key-file service-account-travis-ci.json
install:
  - gcloud config set project $GOOGLE_CLOUD_PROJECT
  - yarn --frozen-lockfile
script:
  - yarn test
deploy:
  provicer: script
  script: ./deploy.sh
  skip_cleanup: false
  on:
    branch: master
